#This is the master snakemake file.
#To run the workflow: snakemake --cores "ncores" "sample_dir/" "outdir/"
#The following structure of input directories is needed: [samples]/[sample]/#.fq

#Import statements:
from snakemake.utils import min_version
min_version("6.0")

#set config file:
configfile: "../config/config.yaml"


###############################################################################
###Execute main snakemake workflow###

#Main rule:
rule all:
    input:
        expand("{sample_dir}{sample}/{sample}_{Rnum}_trimmed.fq.gz",
        sample_dir=config["INPUT_PATH"],
        sample = config["SAMPLES"],
        Rnum=['1', '2'])

#Rule 1: Quality control of input reads:
#Open the module:
module read_qc:
    snakefile:
        "rules/read_qc.smk"

#Run the module:
use rule fastp from read_qc as read_qc_fastp
